language: scala
services:
 - docker
scala:
 - 2.11.8

jdk:
 - oraclejdk8

script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
  - sbt codacyCoverage
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - sbt "docker:publish" # here and not as part of release process because it can take a long time

